### ISSUE TITLE
Blocks turning snow variants went they shouldnt 

### ISSUE THREAD

**Issue by Sunekaer** [trikzon/Snow-Variants#3] opened 2019-05-08 10:49 UTC
Original issue on FTB Github: https://github.com/FTBTeam/FTB-Builders-Paradise/issues/9
Issue:
For example if shooting on a slab or stair with a Shuriken from Tinkers
![image](https://user-images.githubusercontent.com/18720460/57369910-19493180-718f-11e9-9b69-8bd8b3e71ae1.png)

**Comment by Trikzon** [comment] 2019-05-08 23:29
Hi, I will test this later but am confused as to why this would be happening. I only check to see if the player is holding a snow layer from vanilla

**Comment by Trikzon** [comment] 2019-05-09 00:53
Sorry, I have noticed what the problem is. In the current release I accidentally left out an if statement that checks what Item the player is holding. That is a bug I fixed in the next version but I have been unable to get it complete. An update which fixes this issue and updates the model along with various other things will be out within the week.

**Comment by Sunekaer** [comment] 2019-05-09 11:57
Thanks trikzon

**Comment by Sunekaer** [comment] 2019-05-10 15:34
Severnate
I just lost my tinkers pick, I right clicked some stairs, they went snowy and was then destroyed

**Comment by Trikzon** [comment] 2019-05-13 01:02
c0a7c0b0a29998a8ff15e052908ee20e3e945482

**Comment by Trikzon** [comment] 2019-05-13 01:03
c0a7c0b0a29998a8ff15e052908ee20e3e945482
Fixed and now published on curse. Thanks for reporting!

**Closed as completed by Trikzon** 2019-05-13 01:03 UTC
Labels: bug
